[project]
authors = [{ name = "Andy Lo", email = "andylolu24@gmail.com" }]
description = "Add a short description here"
name = "ollm"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = [
    "arxiv-base>=0.17.8,<0.18",
    "kaggle>=1.6.17,<2",
    "scienceplots>=2.1.1,<3",
    "ml-collections>=0.1.1,<0.2",
    "trl>=0.11.3,<0.12",
    "vllm>=0.2.5,<0.3",
    "peft>=0.13.1,<0.14",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "pytorch", "nvidia", "pyg"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
ollm = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pyg = ">=2.5.2,<3"
accelerate = ">=1.0.0,<2"
transformers = ">=4.45.2,<5"
absl-py = ">=2.1.0,<3"
networkx = ">=3.3,<4"
ruff = ">=0.6.9,<0.7"
python = "3.11.*"
uwsgi = ">=2.0.23,<3"
python-dotenv = ">=1.0.1,<2"
graph-tool = ">=2.77,<3"
mypy = ">=1.11.2,<2"
datasets = ">=3.0.1,<4"
tensorboardx = ">=2.6.2.2,<3"
wandb = ">=0.18.1,<0.19"

[tool.mypy]
ignore_missing_imports = true
